services:
  openote_db:
    build:
      dockerfile: db.Dockerfile
    container_name: openote_db
    environment:
      POSTGRES_USER: openuser
      POSTGRES_PASSWORD: openpass
      POSTGRES_DB: openote
    ports:
      - "5432:5432"
    volumes:
      - ./back/res/base.sql:/docker-entrypoint-initdb.d/base.sql # postgres will automatically source sql file her the first time it's initiated
      - ./back/res/entries.sql:/app/entries.sql

  openote_api:
    container_name: openote_api
    restart: on-failure
    depends_on:
      - openote_db

    build:
      dockerfile: api.Dockerfile

    ports:
      - "8000:8000"

    environment:
      OPENOTE_DB_NAME: openote
      OPENOTE_DB_USER: openuser
      OPENOTE_DB_HOST: openote_db
      OPENOTE_DB_PASS: openpass

  openote_front:
    container_name: openote_front
    restart: on-failure
    depends_on:
      - openote_api

    build:
      dockerfile: front.Dockerfile

    ports:
      - "3000:3000"

    environment:
      OPENOTE_API_BASE_URL: "http://localhost:8000" # change to your domain nyame and port for you
